# cloudbuild.yaml
substitutions:
  _REPO_NAME: "my-app"  # or pass from trigger dynamically

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/${_REPO_NAME}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_REPO_NAME}']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_REPO_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_REPO_NAME}'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'
